"""
Uitgebreide uitleg per verbeterstap.

Structuur: STAP_UITLEG[domein][stap_index] = {
    "hoe": korte hoe-te-aanpak,
    "deelacties": lijst concrete deelacties,
    "wie": wie betrekken,
    "valkuil": veelvoorkomende valkuil,
    "resultaat": hoe ziet 'klaar' eruit,
    "norm": gekoppelde norm/bron voor deze specifieke stap,
}

De stap_index correspondeert met de volgorde in MAATREGELEN[domein]["stappen"].
"""

STAP_UITLEG = {
    # ══════════════════════════════════════════════════════════
    # LAAG 1 — MODIFIERS
    # ══════════════════════════════════════════════════════════
    "Governance": {
        0: {  # Benoem één verantwoordelijke (rol)
            "hoe": "Wijs een rol aan — niet een persoon — die eindverantwoordelijk is voor het beheer van derde diensten. Door het aan een rol te koppelen blijft het bestaan als de persoon vertrekt.",
            "deelacties": [
                "Bepaal welke rol het beste past (bijv. informatiemanager, operationeel directeur).",
                "Beschrijf de verantwoordelijkheid in een korte rolbeschrijving (1 A4).",
                "Laat de directie de rol formeel bekrachtigen.",
                "Communiceer de rol intern zodat iedereen weet bij wie men moet zijn.",
            ],
            "wie": "Directie/bestuur (bekrachtiging) en de beoogde rolhouder.",
            "valkuil": "De rol toewijzen aan iemand die er geen tijd of mandaat voor krijgt — dan blijft het symbolisch.",
            "resultaat": "Eén aanwijsbare rol met een vastgelegde verantwoordelijkheid voor ketenrelaties, bekend bij de organisatie.",
            "norm": "COBIT 2019 (EDM01 — Governance Framework), ISO 27001 A.5.2 (rollen en verantwoordelijkheden).",
        },
        1: {  # Leg vast welke beslissingen waar genomen worden
            "hoe": "Maak onderscheid tussen beslissingen die op directieniveau horen (bijv. een kritieke leverancier aangaan) en beslissingen die gedelegeerd kunnen worden (bijv. operationele opvolging).",
            "deelacties": [
                "Inventariseer welke soorten beslissingen voorkomen rond derde diensten.",
                "Classificeer per soort: directie, management of operationeel.",
                "Leg de classificatie vast in een eenvoudige beslismatrix.",
                "Toets de matrix met een paar recente praktijkgevallen.",
            ],
            "wie": "Directie en betrokken managers.",
            "valkuil": "Alles naar de directie tillen (verlamming) of alles delegeren (geen grip op kritieke keuzes).",
            "resultaat": "Een beslismatrix die helder maakt wie waarover beslist bij uitbesteding.",
            "norm": "COBIT 2019 (EDM/APO-domeinen), COSO 2013 (control environment).",
        },
        2: {  # Besluitvormingskader
            "hoe": "Stel een licht besluitvormingskader op dat beschrijft hoe een beslissing over een derde dienst tot stand komt — van afweging tot vastlegging.",
            "deelacties": [
                "Beschrijf de standaardstappen bij het aangaan/wijzigen van een uitbesteding.",
                "Benoem welke criteria meewegen (kritikaliteit, risico, kosten, exit).",
                "Bepaal hoe en waar besluiten worden vastgelegd.",
                "Houd het kort — één pagina is vaak genoeg voor het MKB.",
            ],
            "wie": "Rolhouder governance, met input van inkoop/IT.",
            "valkuil": "Een te zwaar, bureaucratisch kader maken dat in de praktijk wordt overgeslagen.",
            "resultaat": "Een beknopt, gebruikt kader dat besluitvorming navolgbaar maakt.",
            "norm": "COBIT 2019 (APO10 — Managed Vendors), EBA Guidelines (besluitvorming uitbesteding).",
        },
        3: {  # Veranker in overlegcyclus
            "hoe": "Zorg dat ketenrisico's terugkeren op een vast moment in de bestaande overlegcyclus, zodat het geen eenmalige actie is maar onderdeel van de besturing.",
            "deelacties": [
                "Kies een bestaand overleg (bijv. kwartaal-directieoverleg) als ankermoment.",
                "Spreek af welke rapportage daar standaard wordt besproken.",
                "Leg vast wie de rapportage aanlevert en wanneer.",
                "Evalueer na twee cycli of het werkt en stel bij.",
            ],
            "wie": "Directie en rolhouder governance.",
            "valkuil": "Het bij een eenmalige presentatie laten — zonder herhaling verdwijnt de aandacht.",
            "resultaat": "Ketenrisico's staan structureel op de directie-agenda met een vaste rapportage.",
            "norm": "COBIT 2019 (MEA — Monitor, Evaluate, Assess), COSO 2013 (monitoring activities).",
        },
    },
    "Cultuur": {
        0: {  # Vast moment voor risicobespreking
            "hoe": "Creëer een terugkerend, laagdrempelig moment waarop ketenrisico's en incidenten worden besproken — niet als afrekenmoment, maar als leermoment.",
            "deelacties": [
                "Kies een ritme dat past (bijv. maandelijks kort, kwartaal uitgebreid).",
                "Maak het onderdeel van een bestaand overleg om drempels te verlagen.",
                "Bereid een paar concrete casussen voor om het gesprek op gang te brengen.",
                "Houd het kort en concreet, gericht op leren.",
            ],
            "wie": "Teamleiders en medewerkers die met derde diensten werken.",
            "valkuil": "Het gesprek laten verzanden in algemeenheden of het tot een verplicht nummer maken.",
            "resultaat": "Een vast, gewaardeerd moment waarop risico's open op tafel komen.",
            "norm": "Schein (cultuurinterventies), COSO 2013 (control environment).",
        },
        1: {  # Bijna-incidenten zonder schuldvraag
            "hoe": "Bespreek ook situaties die net goed afliepen (bijna-incidenten), en doe dat zonder schuldvraag — dat is de kern van psychologische veiligheid die leren mogelijk maakt.",
            "deelacties": [
                "Maak expliciet dat melden van bijna-incidenten gewaardeerd wordt.",
                "Scheid het leren van de beoordeling van personen.",
                "Deel geleerde lessen breed, niet wie wat fout deed.",
                "Laat leidinggevenden zelf ook bijna-incidenten delen (voorbeeldgedrag).",
            ],
            "wie": "Leidinggevenden (voorbeeldrol) en alle medewerkers.",
            "valkuil": "Bij het eerste incident alsnog naar een schuldige zoeken — dan stopt het melden direct.",
            "resultaat": "Medewerkers melden bijna-incidenten uit zichzelf, omdat het veilig voelt.",
            "norm": "Argyris (double-loop leren), Schein (psychologische veiligheid).",
        },
        2: {  # Geleerde lessen vastleggen en koppelen aan acties
            "hoe": "Zorg dat geleerde lessen niet verdampen: leg ze kort vast en koppel ze aan een concrete actie met eigenaar, anders blijft het bij praten.",
            "deelacties": [
                "Noteer per besproken casus de kernles in één of twee zinnen.",
                "Koppel aan elke les een concrete vervolgactie.",
                "Wijs per actie een eigenaar en termijn toe.",
                "Kom er de volgende sessie kort op terug (is het opgevolgd?).",
            ],
            "wie": "Rolhouder governance en de actie-eigenaren.",
            "valkuil": "Lessen vastleggen maar nooit opvolgen — dan wordt het een dood document.",
            "resultaat": "Een korte, levende lijst van lessen met opgevolgde acties.",
            "norm": "Argyris (double-loop), COSO 2013 (monitoring & remediation).",
        },
        3: {  # Directie geeft het goede voorbeeld
            "hoe": "Cultuur volgt gedrag van de top. Laat de directie risico's serieus nemen, vragen stellen over de keten en zelf het goede voorbeeld geven.",
            "deelacties": [
                "Laat de directie ketenrisico's expliciet benoemen als prioriteit.",
                "Laat hen vragen stellen over derde diensten in overleggen.",
                "Laat hen tijd en middelen vrijmaken voor verbeteracties.",
                "Vier zichtbaar verbeteringen, niet alleen het oplossen van incidenten.",
            ],
            "wie": "Directie/bestuur.",
            "valkuil": "Mooie woorden zonder gedrag — medewerkers prikken daar feilloos doorheen.",
            "resultaat": "Zichtbaar directiegedrag dat risicobewustzijn normaal maakt.",
            "norm": "Schein (leiderschap en cultuur), COSO 2013 (tone at the top).",
        },
    },
    # ══════════════════════════════════════════════════════════
    # LAAG 2 — OPERATIONELE PRAKTIJKEN
    # ══════════════════════════════════════════════════════════
    "Monitoring": {
        0: {  # Inventariseer kritieke diensten
            "hoe": "Bepaal eerst welke derde diensten écht kritiek zijn — niet alles, maar de diensten waarvan uitval direct de bedrijfsvoering raakt.",
            "deelacties": [
                "Lijst alle derde diensten die de organisatie gebruikt.",
                "Bepaal per dienst de impact van uitval op primaire processen.",
                "Markeer de diensten met hoge impact als kritiek.",
                "Valideer de lijst met de business (niet alleen IT).",
            ],
            "wie": "IT en proceseigenaren uit de business.",
            "valkuil": "Alles kritiek noemen — dan verlies je focus en wordt monitoring onhoudbaar.",
            "resultaat": "Een korte lijst van écht kritieke derde diensten, gedragen door de business.",
            "norm": "ISO 27001 A.5.9 (inventarisatie van assets), EBA (kritieke functies).",
        },
        1: {  # Definieer KPI's/KRI's
            "hoe": "Bepaal per kritieke dienst een paar meetbare indicatoren die iets zeggen over gezondheid en risico — houd het beperkt en zinvol.",
            "deelacties": [
                "Kies per dienst 2-3 indicatoren (bijv. beschikbaarheid, responstijd, incidenten).",
                "Definieer drempelwaarden (wanneer is iets een afwijking?).",
                "Bepaal de bron van de data (leverancier, eigen systeem).",
                "Spreek af hoe vaak gemeten wordt.",
            ],
            "wie": "IT en de rolhouder governance.",
            "valkuil": "Te veel indicatoren kiezen die niemand bijhoudt of begrijpt.",
            "resultaat": "Een handvol betekenisvolle, meetbare indicatoren per kritieke dienst.",
            "norm": "ISO 27001 A.5.22 (monitoring leveranciers), NIST SP 800-207.",
        },
        2: {  # Richt rapportage/dashboard in
            "hoe": "Maak de indicatoren zichtbaar in een eenvoudige rapportage of dashboard, zodat afwijkingen opvallen zonder dat iemand actief hoeft te zoeken.",
            "deelacties": [
                "Kies een praktisch middel (kan een simpel overzicht of bestaand tool zijn).",
                "Zorg dat afwijkingen visueel opvallen (kleur, signalering).",
                "Maak het toegankelijk voor wie het nodig heeft.",
                "Begin klein — een werkend basis-dashboard is beter dan een perfect plan.",
            ],
            "wie": "IT, eventueel met een tool-leverancier.",
            "valkuil": "Een te complex dashboard bouwen dat niemand onderhoudt of bekijkt.",
            "resultaat": "Een werkend, eenvoudig overzicht waarin afwijkingen direct opvallen.",
            "norm": "ISO 27001 A.5.22, NIST SP 800-207 (continuous monitoring).",
        },
        3: {  # Koppel aan opvolgproces
            "hoe": "Monitoring heeft alleen zin als afwijkingen tot actie leiden. Leg vast wie wat doet wanneer een indicator een alarm geeft.",
            "deelacties": [
                "Bepaal per indicator wie het alarm ontvangt.",
                "Beschrijf welke actie hoort bij welke afwijking.",
                "Leg escalatie vast (wat als het niet wordt opgelost?).",
                "Test het opvolgproces met een gesimuleerde afwijking.",
            ],
            "wie": "IT, rolhouder governance en betrokken proceseigenaren.",
            "valkuil": "Alarmen laten binnenkomen zonder dat iemand verantwoordelijk is voor opvolging.",
            "resultaat": "Elke afwijking leidt tot een duidelijke, belegde actie.",
            "norm": "ISO 27001 A.5.24-A.5.26 (incident management), DORA.",
        },
    },
    "BCM": {
        0: {  # Identificeer processen die stilvallen
            "hoe": "Bepaal welke bedrijfsprocessen direct stilvallen als een kritieke leverancier uitvalt — dit is de basis voor elk continuïteitsplan.",
            "deelacties": [
                "Breng per kritieke derde dienst in kaart welke processen ervan afhangen.",
                "Bepaal de impact van uitval per proces (financieel, klant, compliance).",
                "Prioriteer de processen met de grootste impact.",
                "Betrek de business om blinde vlekken te vinden.",
            ],
            "wie": "Proceseigenaren en IT.",
            "valkuil": "Alleen naar IT-impact kijken en de bedrijfsprocessen vergeten.",
            "resultaat": "Inzicht in welke processen bij welke leveranciersuitval stilvallen.",
            "norm": "ISO 22301 (business impact analyse), DORA.",
        },
        1: {  # Bepaal RTO/RPO
            "hoe": "Bepaal per kritiek proces hoe snel het hersteld moet zijn (RTO) en hoeveel dataverlies acceptabel is (RPO). Dit stuurt alle herstelmaatregelen.",
            "deelacties": [
                "Bepaal per proces de maximaal aanvaardbare uitvalduur (RTO).",
                "Bepaal het maximaal aanvaardbare dataverlies (RPO).",
                "Toets of deze doelen haalbaar zijn met de huidige middelen.",
                "Leg de doelen vast en deel ze met de leverancier.",
            ],
            "wie": "Proceseigenaren, IT en directie (afweging acceptabel risico).",
            "valkuil": "RTO/RPO bepalen zonder te toetsen of ze realistisch haalbaar zijn.",
            "resultaat": "Vastgelegde, gedragen hersteldoelstellingen per kritiek proces.",
            "norm": "ISO 22301 (RTO/RPO), DORA (operationele weerbaarheid).",
        },
        2: {  # Werk fallback-scenario's uit
            "hoe": "Bepaal per kritiek proces wat je doet als de leverancier uitvalt — een handmatig alternatief, een tweede leverancier, of een noodprocedure.",
            "deelacties": [
                "Bedenk per proces een realistisch fallback (handmatig, alternatief, uitstel).",
                "Beschrijf wie wat doet tijdens de uitval.",
                "Zorg dat benodigde middelen/contacten vooraf geregeld zijn.",
                "Leg het scenario kort en vindbaar vast.",
            ],
            "wie": "Proceseigenaren en IT.",
            "valkuil": "Een theoretisch plan dat in de praktijk niet uitvoerbaar blijkt.",
            "resultaat": "Per kritiek proces een concreet, uitvoerbaar fallback-scenario.",
            "norm": "ISO 22301 (continuity strategies), DORA.",
        },
        3: {  # Test periodiek
            "hoe": "Een ongetest plan is een aanname. Test de scenario's periodiek met een oefening, en gebruik de uitkomst om het plan te verbeteren.",
            "deelacties": [
                "Plan een eenvoudige tabletop-oefening (doorpraten van een scenario).",
                "Voer de oefening uit en noteer wat niet werkte.",
                "Pas het plan aan op basis van de bevindingen.",
                "Herhaal periodiek (bijv. jaarlijks of na grote wijzigingen).",
            ],
            "wie": "Alle betrokkenen bij het scenario, geleid door rolhouder governance.",
            "valkuil": "De test eindeloos uitstellen omdat 'er nu geen tijd voor is'.",
            "resultaat": "Een getest, werkend plan en betrokkenen die weten wat te doen.",
            "norm": "ISO 22301 (exercising & testing), DORA (testverplichtingen).",
        },
    },
    "Awareness": {
        0: {  # Maak kritieke diensten inzichtelijk per team
            "hoe": "Zorg dat teams weten van welke derde diensten hun werk afhangt — bewustzijn begint bij weten waar je afhankelijk van bent.",
            "deelacties": [
                "Maak per team inzichtelijk welke derde diensten zij gebruiken.",
                "Markeer welke daarvan kritiek zijn voor hun werk.",
                "Bespreek dit kort met elk team.",
                "Houd het overzicht actueel bij nieuwe diensten.",
            ],
            "wie": "Teamleiders en de rolhouder governance.",
            "valkuil": "Een centrale lijst maken die nooit bij de teams zelf landt.",
            "resultaat": "Elk team weet van welke kritieke derde diensten het afhankelijk is.",
            "norm": "ISO 27001 A.6.3 (awareness), NIS2.",
        },
        1: {  # Gerichte voorlichting
            "hoe": "Geef voorlichting die aansluit op de eigen situatie van medewerkers — concreet en herkenbaar, niet algemeen.",
            "deelacties": [
                "Maak de voorlichting specifiek voor de eigen derde diensten.",
                "Gebruik herkenbare voorbeelden uit de eigen praktijk.",
                "Leg uit wat de eigen rol is in het beheersen van risico's.",
                "Houd sessies kort en interactief.",
            ],
            "wie": "Rolhouder governance, eventueel met externe ondersteuning.",
            "valkuil": "Generieke e-learning die niet aansluit op de eigen keten.",
            "resultaat": "Medewerkers begrijpen de risico's van hún derde diensten.",
            "norm": "ISO 27001 A.6.3, NIS2 (awareness).",
        },
        2: {  # Oefen handelingsperspectief
            "hoe": "Zorg dat medewerkers niet alleen weten dát er risico's zijn, maar ook wat ze concreet moeten doen bij een incident of uitval.",
            "deelacties": [
                "Beschrijf per kritieke dienst wat te doen bij uitval (wie bel je?).",
                "Oefen dit met een korte, realistische casus.",
                "Maak handelingskaarten of een eenvoudig stappenplan.",
                "Zorg dat de info vindbaar is op het moment dat het nodig is.",
            ],
            "wie": "Teamleiders en medewerkers.",
            "valkuil": "Kennis overdragen zonder het handelen te oefenen — onder druk valt men terug op gewoonte.",
            "resultaat": "Medewerkers weten concreet hoe te handelen bij uitval.",
            "norm": "ISO 27001 A.6.3, ISO 22301 (awareness & oefening).",
        },
        3: {  # Herhaal periodiek
            "hoe": "Bewustzijn vervaagt en personeel wisselt. Herhaal de awareness periodiek en sluit aan op actuele incidenten om het levend te houden.",
            "deelacties": [
                "Plan periodieke herhaling (bijv. jaarlijks of na incidenten).",
                "Neem nieuwe medewerkers mee in het onboarding-traject.",
                "Gebruik actuele incidenten (intern/extern) als haakje.",
                "Meet of het bewustzijn op peil blijft.",
            ],
            "wie": "Rolhouder governance en HR (onboarding).",
            "valkuil": "Eenmalig trainen en denken dat het klaar is.",
            "resultaat": "Awareness blijft op peil, ook bij personeelsverloop.",
            "norm": "ISO 27001 A.6.3, NIS2.",
        },
    },
    # ══════════════════════════════════════════════════════════
    # LAAG 3 — IMPLEMENTATIES
    # ══════════════════════════════════════════════════════════
    "SLA": {
        0: {
            "hoe": "Verzamel en orden de bestaande contracten met kritieke leveranciers, zodat je weet wat er nu écht is afgesproken.",
            "deelacties": [
                "Verzamel alle contracten/SLA's met kritieke leveranciers.",
                "Noteer per contract de looptijd en opzegtermijn.",
                "Markeer welke verlopen of binnenkort aflopen.",
                "Sla ze centraal en vindbaar op.",
            ],
            "wie": "Inkoop/contractbeheer en de rolhouder governance.",
            "valkuil": "Aannemen dat de afspraken bekend zijn zonder de contracten echt te lezen.",
            "resultaat": "Een actueel overzicht van wat er nu contractueel is geregeld.",
            "norm": "ISO 27001 A.5.20 (afspraken met leveranciers), EBA (uitbestedingsregister).",
        },
        1: {
            "hoe": "Vergelijk de bestaande contracten met wat nodig is: ontbreken er afspraken over wijziging, audit, herstel of exit?",
            "deelacties": [
                "Toets elk contract op clausules voor change notification.",
                "Toets op auditrechten en rapportage.",
                "Toets op herstelafspraken (RTO/RPO) en exit/overstap.",
                "Maak een lijst van de belangrijkste hiaten.",
            ],
            "wie": "Contractbeheer, IT en eventueel juridisch.",
            "valkuil": "Alleen op prijs en service letten en de beheersclausules vergeten.",
            "resultaat": "Een overzicht van ontbrekende clausules per kritiek contract.",
            "norm": "EBA Guidelines, DORA (contractuele waarborgen), ISO 27001 A.5.20.",
        },
        2: {
            "hoe": "Vul de hiaten aan bij een natuurlijk moment — contractverlenging of -herziening — want tussentijds openbreken is lastig.",
            "deelacties": [
                "Prioriteer de contracten met de grootste hiaten en hoogste kritikaliteit.",
                "Bereid de gewenste clausules voor (gebruik standaardteksten).",
                "Onderhandel bij verlenging of herziening.",
                "Leg de nieuwe afspraken vast.",
            ],
            "wie": "Contractbeheer/inkoop, met mandaat van de rolhouder governance.",
            "valkuil": "Wachten op het 'perfecte moment' dat nooit komt — koppel het aan de contractcyclus.",
            "resultaat": "Kritieke contracten bevatten de noodzakelijke beheersclausules.",
            "norm": "EBA Guidelines, DORA, ISO 27001 A.5.20.",
        },
        3: {
            "hoe": "Een contract is pas waardevol als naleving wordt getoetst. Leg vast hoe en wanneer je controleert of de leverancier zijn afspraken nakomt.",
            "deelacties": [
                "Bepaal per contract hoe naleving wordt getoetst (rapportage, gesprek, audit).",
                "Plan periodieke evaluatiemomenten met de leverancier.",
                "Koppel afwijkingen aan opvolging.",
                "Documenteer de evaluaties.",
            ],
            "wie": "Contractbeheer en rolhouder governance.",
            "valkuil": "Het contract tekenen en in de la leggen tot er een probleem is.",
            "resultaat": "Naleving van SLA's wordt periodiek en aantoonbaar getoetst.",
            "norm": "EBA Guidelines (monitoring), DORA, ISO 27001 A.5.22.",
        },
    },
    "Beveiliging": {
        0: {
            "hoe": "Breng in kaart welke koppelingen er met derde diensten bestaan en welke toegangen daarbij horen — je kunt alleen beheersen wat je kent.",
            "deelacties": [
                "Inventariseer alle koppelingen/integraties met derde diensten.",
                "Noteer per koppeling welke toegang en data erbij horen.",
                "Markeer de koppelingen met toegang tot gevoelige data.",
                "Houd het overzicht actueel.",
            ],
            "wie": "IT/security.",
            "valkuil": "Schaduw-IT en oude koppelingen over het hoofd zien.",
            "resultaat": "Een actueel overzicht van koppelingen en bijbehorende toegangen.",
            "norm": "ISO 27001 A.8 (asset & access), CIS Controls.",
        },
        1: {
            "hoe": "Pas least-privilege toe: elke koppeling en gebruiker krijgt alleen de toegang die strikt nodig is, expliciet toegekend.",
            "deelacties": [
                "Toets per koppeling of de toegang echt nodig is.",
                "Verwijder of beperk overbodige rechten.",
                "Leg vast wie welke toegang heeft en waarom.",
                "Pas zero-trust-principes toe (verifieer altijd, vertrouw nooit impliciet).",
            ],
            "wie": "IT/security.",
            "valkuil": "Brede rechten laten staan 'voor het gemak' — dat is precies het risico.",
            "resultaat": "Toegang is beperkt tot het noodzakelijke en expliciet toegekend.",
            "norm": "NIST SP 800-207 (zero trust), CIS Controls, ISO 27001 A.8.",
        },
        2: {
            "hoe": "Richt logging en monitoring in op de koppelingen, zodat verdacht of afwijkend gebruik zichtbaar wordt.",
            "deelacties": [
                "Zet logging aan op de kritieke koppelingen.",
                "Bepaal wat normaal gedrag is en wat een signaal.",
                "Koppel signalen aan de monitoring uit Laag 2.",
                "Bewaar logs lang genoeg voor onderzoek.",
            ],
            "wie": "IT/security, afgestemd met monitoring.",
            "valkuil": "Loggen zonder ooit naar de logs te kijken.",
            "resultaat": "Afwijkend gebruik van koppelingen wordt zichtbaar en opvolgbaar.",
            "norm": "ISO 27001 A.8.15-A.8.16 (logging & monitoring), NIST SP 800-207.",
        },
        3: {
            "hoe": "Toegang en beveiliging verouderen. Toets periodiek of de maatregelen nog kloppen en herzie toegangsrechten.",
            "deelacties": [
                "Plan periodieke herziening van toegangsrechten.",
                "Verwijder toegang van vertrokken leveranciers/medewerkers.",
                "Test de beveiliging (bijv. via een review of pentest).",
                "Documenteer de herzieningen.",
            ],
            "wie": "IT/security en rolhouder governance.",
            "valkuil": "Privilege creep — rechten stapelen zich op omdat niemand opruimt.",
            "resultaat": "Toegang blijft beperkt en actueel; beveiliging is getoetst.",
            "norm": "ISO 27001 A.8 (access review), CIS Controls, NIST SP 800-207.",
        },
    },
    "Documentatie": {
        0: {
            "hoe": "Leg per kritieke derde dienst de belangrijkste processen en afspraken vast — begin bij de diensten die er het meest toe doen.",
            "deelacties": [
                "Bepaal per kritieke dienst wat vastgelegd moet worden.",
                "Beschrijf de kernprocessen en afspraken beknopt.",
                "Gebruik een eenvoudige, consistente structuur.",
                "Begin met de meest kritieke diensten.",
            ],
            "wie": "Proceseigenaren en rolhouder governance.",
            "valkuil": "Alles tot in detail willen documenteren en daardoor nooit afkomen.",
            "resultaat": "De kritieke diensten zijn op hoofdlijnen gedocumenteerd.",
            "norm": "ISO 27001 (gedocumenteerde informatie), EBA (uitbestedingsregister).",
        },
        1: {
            "hoe": "Bepaal waar documentatie woont en wie haar beheert — zonder eigenaar veroudert documentatie snel.",
            "deelacties": [
                "Kies één centrale, vindbare plek voor de documentatie.",
                "Wijs per document een beheerder aan.",
                "Spreek af hoe vaak het wordt herzien.",
                "Zorg voor versiebeheer.",
            ],
            "wie": "Rolhouder governance en documentbeheerders.",
            "valkuil": "Documentatie verspreid over mailboxen en lokale schijven.",
            "resultaat": "Documentatie staat centraal, met beheerders en versiebeheer.",
            "norm": "ISO 27001 (control of documented information).",
        },
        2: {
            "hoe": "Koppel documentatie aan wijzigingen: elke contract- of proceswijziging triggert een update, zodat documentatie actueel blijft.",
            "deelacties": [
                "Maak het bijwerken van documentatie onderdeel van wijzigingsprocessen.",
                "Spreek af wie de update doet bij een wijziging.",
                "Controleer periodiek of documentatie nog klopt.",
                "Verwijder verouderde documentatie.",
            ],
            "wie": "Proceseigenaren en documentbeheerders.",
            "valkuil": "Documentatie maken voor een audit en daarna nooit meer bijwerken.",
            "resultaat": "Documentatie blijft synchroon met de werkelijke processen.",
            "norm": "ISO 27001 (documented information), EBA.",
        },
        3: {
            "hoe": "Zorg dat documentatie vindbaar is voor wie haar nodig heeft — anders bestaat ze wel maar wordt ze niet gebruikt.",
            "deelacties": [
                "Maak de documentatie toegankelijk voor de juiste mensen.",
                "Zorg voor een logische structuur en zoekbaarheid.",
                "Toets of mensen de documentatie daadwerkelijk vinden.",
                "Balanceer toegankelijkheid met vertrouwelijkheid.",
            ],
            "wie": "Documentbeheerders en IT.",
            "valkuil": "Documentatie zo afschermen dat niemand er meer bij kan.",
            "resultaat": "Wie de documentatie nodig heeft, vindt haar snel.",
            "norm": "ISO 27001 (availability of documented information).",
        },
    },
    "Externe borging": {
        0: {
            "hoe": "Bepaal van welke kritieke leveranciers assurance-rapporten (SOC 2 / ISAE 3402) beschikbaar zijn — niet elke leverancier heeft ze.",
            "deelacties": [
                "Inventariseer per kritieke leverancier of er assurance-rapporten zijn.",
                "Bepaal welk type rapport (SOC 2 type I/II, ISAE 3402).",
                "Vraag ontbrekende rapporten op of bespreek alternatieven.",
                "Noteer de geldigheidsperiode van elk rapport.",
            ],
            "wie": "Rolhouder governance en inkoop.",
            "valkuil": "Aannemen dat een rapport bestaat zonder het op te vragen.",
            "resultaat": "Overzicht van beschikbare assurance-rapporten per kritieke leverancier.",
            "norm": "ISAE 3402 / SOC 2, DORA (toezicht op derden).",
        },
        1: {
            "hoe": "Beoordeel de rapporten inhoudelijk — archiveren alleen geeft schijnzekerheid. Lees wat er werkelijk in staat.",
            "deelacties": [
                "Lees het rapport, niet alleen de conclusie.",
                "Let op de scope: wat is wél en niet getoetst.",
                "Noteer de bevindingen en uitzonderingen.",
                "Bepaal wat de bevindingen betekenen voor jouw organisatie.",
            ],
            "wie": "Rolhouder governance, eventueel met auditkennis.",
            "valkuil": "Het rapport ongelezen archiveren omdat 'er een rapport is'.",
            "resultaat": "De rapporten zijn inhoudelijk beoordeeld op relevantie en bevindingen.",
            "norm": "ISAE 3402 / SOC 2 (beoordeling), DORA.",
        },
        2: {
            "hoe": "Toets de bevindingen tegen je eigen risico's en processen — hiervoor heb je je eigen documentatie nodig (vandaar de type-S afhankelijkheid).",
            "deelacties": [
                "Vergelijk de uitzonderingen met je eigen kritieke processen.",
                "Bepaal of een bevinding een reëel risico voor jou vormt.",
                "Toets of complementaire controls aan jouw kant nodig zijn.",
                "Leg de afweging vast.",
            ],
            "wie": "Rolhouder governance en proceseigenaren.",
            "valkuil": "Bevindingen niet kunnen duiden omdat je eigen processen niet gedocumenteerd zijn.",
            "resultaat": "Je weet welke leveranciersbevindingen voor jou risico vormen.",
            "norm": "ISAE 3402 (complementary user entity controls), DORA.",
        },
        3: {
            "hoe": "Volg tekortkomingen actief op bij de leverancier — borging zonder opvolging verandert niets.",
            "deelacties": [
                "Bespreek relevante bevindingen met de leverancier.",
                "Maak afspraken over herstel en termijn.",
                "Volg op of het herstel daadwerkelijk plaatsvindt.",
                "Neem het mee in de periodieke leveranciersevaluatie.",
            ],
            "wie": "Rolhouder governance en contractbeheer.",
            "valkuil": "Bevindingen signaleren maar nooit met de leverancier bespreken.",
            "resultaat": "Tekortkomingen bij leveranciers worden actief opgevolgd.",
            "norm": "DORA (toezicht & opvolging), ISAE 3402.",
        },
    },
    "Normenkoppeling": {
        0: {
            "hoe": "Bepaal welke regelgeving van toepassing is op jouw organisatie en haar keten — AVG geldt breed, NIS2 en DORA sectorafhankelijk.",
            "deelacties": [
                "Inventariseer welke regelgeving op de organisatie van toepassing is.",
                "Bepaal welke eisen doorwerken naar derde diensten.",
                "Raadpleeg zo nodig juridische expertise.",
                "Leg de van toepassing zijnde kaders vast.",
            ],
            "wie": "Rolhouder governance, juridisch/compliance.",
            "valkuil": "Aannemen dat regelgeving 'een leveranciersprobleem' is — de eindverantwoordelijkheid blijft bij jou.",
            "resultaat": "Helder welke regelgeving op de keten van toepassing is.",
            "norm": "AVG, NIS2, DORA.",
        },
        1: {
            "hoe": "Vertaal de wettelijke eisen naar concrete afspraken in de leverancierscontracten — hiervoor heb je de SLA-basis nodig (type-S).",
            "deelacties": [
                "Vertaal elke relevante eis naar een concrete contractuele afspraak.",
                "Neem de afspraken op in SLA's (bouwt voort op SLA-domein).",
                "Bepaal welk bewijs de leverancier moet leveren.",
                "Stem af met juridisch waar nodig.",
            ],
            "wie": "Compliance, contractbeheer en juridisch.",
            "valkuil": "Compliance claimen zonder het in contracten te verankeren.",
            "resultaat": "Wettelijke eisen zijn vertaald naar afdwingbare afspraken.",
            "norm": "AVG (verwerkersovereenkomst), NIS2, DORA.",
        },
        2: {
            "hoe": "Leg vast hoe naleving wordt aangetoond — toezichthouders vragen niet of het geregeld is, maar of je het kunt aantonen.",
            "deelacties": [
                "Bepaal per eis welk bewijs naleving aantoont.",
                "Verzamel en bewaar dit bewijs gestructureerd.",
                "Koppel aan de documentatie (Laag 3).",
                "Maak het bewijs vindbaar voor een eventuele toets.",
            ],
            "wie": "Compliance en documentbeheer.",
            "valkuil": "Naleving niet kunnen aantonen omdat het bewijs ontbreekt of verspreid is.",
            "resultaat": "Naleving is aantoonbaar met vindbaar, gestructureerd bewijs.",
            "norm": "AVG (accountability), NIS2, DORA.",
        },
        3: {
            "hoe": "Regelgeving verandert. Toets periodiek of je nog voldoet en actualiseer bij nieuwe of gewijzigde eisen.",
            "deelacties": [
                "Plan periodieke toetsing van de naleving.",
                "Volg wijzigingen in relevante regelgeving.",
                "Actualiseer afspraken en bewijs bij wijzigingen.",
                "Rapporteer de status aan de directie.",
            ],
            "wie": "Compliance en rolhouder governance.",
            "valkuil": "Eenmalig compliant zijn en aannemen dat het zo blijft.",
            "resultaat": "Naleving wordt periodiek getoetst en blijft actueel.",
            "norm": "AVG, NIS2, DORA (doorlopende naleving).",
        },
    },
}
